##开发环境私有配置
server:
  port: 8082
  address:
  context-parameters: # Servlet context init parameters, e.g. server.context-parameters.a: alpha
  context-path: # the context path, defaults to '/'
  servlet-path: # the servlet path, defaults to '/'
  session:
    timeout: 30

spring:
  thymeleaf:
    cache: false

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  level:
    org.springframework.security: DEBUG
    com.panda: DEBUG